In [56]:
import numpy as np

In [57]:
## Create array using numpy
## create a 1D array
arr1 =np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [58]:
arr2 =np.array([[1,2,3,4,5]])
arr2.reshape(1,5)


array([[1, 2, 3, 4, 5]])

In [59]:
# 2d arrays
arr2 =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [60]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [61]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [62]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
## Attributes of numpy arrays

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n", arr)
print("Shape:", arr.shape) # Output: (3, 3)

print("Number of Dimensions:", arr.ndim) # Output: 2
print("Size (number of elements):", arr.size) # Output: 9
print("Item Size (in bytes):", arr.itemsize) # Output: 8 (or 4 depending on your system)
print("Data Type:", arr.dtype) # Output: int64 (or int32 depending on your system)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Number of Dimensions: 2
Size (number of elements): 9
Item Size (in bytes): 8
Data Type: int64


In [64]:
## numpy vectorized operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element-wise addition
print("Addition:", arr1 + arr2) # Output: [11 22 33 44 55]
# Element-wise subtraction
print("Subtraction:", arr2 - arr1) # Output: [ 9 18 27 36 45]
# Element-wise multiplication
print("Multiplication:", arr1 * arr2) # Output: [ 10  40  90 160 250]
# Element-wise division
print("Division:", arr2 / arr1) # Output: [10. 10. 10. 10. 10.]
# Element-wise exponentiation
print("Exponentiation:", arr1 ** 2) # Output: [ 1  4  9 16 25]
# Element-wise square root
print("Square Root:", np.sqrt(arr2)) # Output: [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]

Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]
Exponentiation: [ 1  4  9 16 25]
Square Root: [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


In [65]:
 ## Universal functions  in numpy

arr = np.array([1, 4, 9, 16, 25])

# Element-wise exponentiation
print("Exponentiation:", arr ** 2)

# Element-wise square root
print("Square Root:", np.sqrt(arr))

# sin function
print("Sine:", np.sin(arr))

# natural logarithm
print("Natural Logarithm:", np.log(arr))




Exponentiation: [  1  16  81 256 625]
Square Root: [1. 2. 3. 4. 5.]
Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
Natural Logarithm: [0.         1.38629436 2.19722458 2.77258872 3.21887582]


In [66]:
 ## arra slicing and  indexing in numpy

arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[11, 12, 13, 14, 15]])

print("Original Array:\n", arr)



Original Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [67]:
# Accessing elements
arr[0] [0]

np.int64(1)

In [68]:
arr[1:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [69]:
# modifying elements

arr[0,0]=100
print(arr)

[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]


In [70]:
arr[1:]=50
print(arr)

[[100   2   3   4   5]
 [ 50  50  50  50  50]
 [ 50  50  50  50  50]]


In [71]:
## statistical concepts--Normalization
## to have a mean of 0 and standard deviation of 1

data = np.array([10, 20, 30, 40, 50])

## Calculate mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

## Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized Data:", normalized_data)

Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [72]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Calculate mean
mean = np.mean(data)
print("Mean:", mean)

# Calculate median
median = np.median(data)
print("Median:", median)

# Calculate standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Calculate variance
variance = np.var(data)
print("variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
variance: 8.25


In [73]:
# Logical operations in numpy

data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data > 5) & (data < 8)]

# we can use and , or operators as well




array([6, 7])